development:
  sessions:
    default:
      database: development
      hosts:
        - 192.168.0.122:27017
production:
  sessions:
    default:
      database: production
      hosts:
        - 192.168.0.122:27017
test:
  sessions:
    default:
      database: test
      hosts:
        - 192.168.0.122:27017
