development:
  sessions:
    default:
      database: mongoid
      hosts:
        - 192.168.0.122:27017
production:
  sessions:
    default:
      database: mongoid
      hosts:
        - 192.168.0.122:27017
